apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "theia.fullname" . }}
  labels:
    {{- include "theia.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "theia.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  template:
    metadata:
      labels:
      {{- include "theia.selectorLabels" . | nindent 6 }}
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      volumes:
      - name: {{ include "theia.fullname" . }}-volume
        persistentVolumeClaim:
           claimName: {{ include "theia.fullname" . }}-disco

      containers:
      - image: {{ .Values.image.repository }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /home/project
          name: {{ include "theia.fullname" . }}-volume
