apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "theia.fullname" . }}-disco
spec:
  accessModes:
  - {{ .Values.persistentVolumeClaim.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storage }}
  storageClassName: {{ .Values.persistentVolumeClaim.storageClassName }}